version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    command: daphne -b 0.0.0.0 -p 8000 settings.asgi:application

  celery_worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A settings worker -l info

  celery_beat:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A settings beat -l info

  flower:
    build: .
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A settings flower --basic-auth=$BLOG_FLOWER_USER:$BLOG_FLOWER_PASSWORD
