# Generated by Django 6.0.1 on 2026-03-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_language_user_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timezone',
            new_name='preferred_timezone',
        ),
    ]
