# Generated by Django 6.0.1 on 2026-04-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_preferred_language_user_preferred_timezone"),
        ("users", "0003_rename_timezone_user_preferred_timezone"),
    ]

    operations = []
